"""Orchestrate ``cargo plushie build`` from the Python SDK.

The build flow:

1. Discover native widgets from ``[tool.plushie.extensions]`` in
   ``pyproject.toml``.
2. Ensure each widget crate's ``Cargo.toml`` declares the required
   ``[package.metadata.plushie.widget]`` block so ``cargo-plushie`` can
   discover it via ``cargo metadata``.
3. Write a virtual app ``Cargo.toml`` under
   ``build/plushie-renderer-spec/`` wiring every widget crate as a
   path dependency, plus an app-level ``[package.metadata.plushie]``
   block carrying ``binary_name`` and ``source_path``.
4. Shell out to ``cargo plushie build --manifest-path <spec>/Cargo.toml``.
5. Install the resulting binary into the project-local renderer location so
   :func:`plushie.binary.resolve` picks it up.
"""

from __future__ import annotations

import os
import shutil
import stat
import subprocess
import sys
from pathlib import Path

from plushie.binary import download_dir, download_name
from plushie.cargo_plushie import resolve_cargo_plushie
from plushie.native_widget import NativeWidget

SPEC_DIR = Path("build") / "plushie-renderer-spec"
"""Scratch directory (under the project) for the virtual app Cargo.toml."""

WIDGET_META_HEADER = "[package.metadata.plushie.widget]"


def write_widget_metadata(widget: NativeWidget) -> None:
    """Ensure ``widget.rust_crate/Cargo.toml`` declares the widget metadata.

    ``cargo-plushie`` discovers widgets by scanning the dep graph for a
    ``[package.metadata.plushie.widget]`` block carrying ``type_name``
    and ``constructor``. When the Python SDK owns the declaration (via
    :class:`NativeWidget`), the widget's Cargo.toml may not have been
    authored with that block. Inject it when missing, or replace it in
    place when already present, so the two sources of truth stay
    synchronized.
    """
    cargo_path = Path(widget.rust_crate) / "Cargo.toml"
    if not cargo_path.is_file():
        raise FileNotFoundError(
            f"widget crate {widget.kind!r} has no Cargo.toml at {cargo_path}"
        )

    original = cargo_path.read_text()
    body = _strip_widget_metadata_block(original)

    new_block = (
        "\n"
        f"{WIDGET_META_HEADER}\n"
        f'type_name = "{widget.kind}"\n'
        f'constructor = "{widget.rust_constructor}"\n'
    )

    updated = body.rstrip() + "\n" + new_block
    if updated != original:
        cargo_path.write_text(updated)


def _strip_widget_metadata_block(content: str) -> str:
    """Remove any existing ``[package.metadata.plushie.widget]`` section."""
    lines = content.splitlines(keepends=True)
    out: list[str] = []
    skipping = False
    for line in lines:
        stripped = line.strip()
        if stripped == WIDGET_META_HEADER:
            skipping = True
            continue
        if skipping and stripped.startswith("[") and stripped.endswith("]"):
            skipping = False
        if not skipping:
            out.append(line)
    return "".join(out)


def write_spec_cargo_toml(
    widgets: list[NativeWidget],
    *,
    binary_name: str,
    source_path: str | None,
    spec_dir: Path = SPEC_DIR,
) -> Path:
    """Write the virtual app ``Cargo.toml`` that drives ``cargo plushie build``.

    The generated crate is a no-op stub: its role is to gather the
    widget crates as path dependencies and carry the
    ``[package.metadata.plushie]`` block that ``cargo-plushie``
    reads. ``cargo-plushie`` then discovers each widget crate's own
    ``[package.metadata.plushie.widget]`` block via ``cargo metadata``.

    Args:
        widgets: Native widget definitions sourced from pyproject.toml.
        binary_name: Custom renderer binary name to pass through as
            ``binary_name`` metadata.
        source_path: Optional absolute path to a plushie-rust checkout.
            ``cargo-plushie`` uses this to patch internal crates onto
            the local workspace.
        spec_dir: Directory (relative or absolute) where the spec
            Cargo.toml is written.

    Returns:
        Path to the written ``Cargo.toml``.
    """
    spec_dir.mkdir(parents=True, exist_ok=True)
    src_dir = spec_dir / "src"
    src_dir.mkdir(parents=True, exist_ok=True)

    # cargo-plushie expects the spec crate to be a valid Cargo package
    # even though it never runs the stub. Empty lib.rs keeps it cheap.
    lib_rs = src_dir / "lib.rs"
    if not lib_rs.exists():
        lib_rs.write_text("// generated by plushie; left intentionally empty\n")

    spec_abs = spec_dir.resolve()
    dep_lines: list[str] = []
    for widget in widgets:
        crate_path = Path(widget.rust_crate).resolve()
        crate_name = Path(widget.rust_crate).name
        rel = os.path.relpath(crate_path, spec_abs)
        dep_lines.append(f'{crate_name} = {{ path = "{rel}" }}')

    deps_block = "\n".join(dep_lines) if dep_lines else ""

    metadata_lines = [
        "[package.metadata.plushie]",
        f'binary_name = "{binary_name}"',
    ]
    if source_path:
        # cargo-plushie accepts absolute paths; store the resolved form
        # so invocations from other cwds still work.
        resolved_source = os.path.abspath(source_path)
        metadata_lines.append(f'source_path = "{resolved_source}"')
    metadata_block = "\n".join(metadata_lines)

    # Package name must be a valid Cargo identifier. Dash-to-underscore
    # mirrors Cargo's own convention for derived names.
    package_name = binary_name.replace("-", "_")

    content = (
        "# Generated by plushie. Do not edit; re-run `python -m plushie build`.\n"
        "[package]\n"
        f'name = "{package_name}-renderer-spec"\n'
        'version = "0.0.0"\n'
        'edition = "2024"\n'
        "publish = false\n"
        "\n"
        "[lib]\n"
        'path = "src/lib.rs"\n'
        "\n"
        "[dependencies]\n"
        f"{deps_block}\n"
        "\n"
        f"{metadata_block}\n"
    )

    cargo_path = spec_dir / "Cargo.toml"
    cargo_path.write_text(content)
    return cargo_path


def install_built_binary(
    spec_dir: Path,
    *,
    binary_name: str,
    release: bool,
    bin_file: str | None,
) -> Path:
    """Copy the binary produced by ``cargo plushie build`` into place.

    ``cargo-plushie`` drives a generated renderer workspace whose
    ``output_dir`` is ``<spec_dir>/target/plushie-renderer/``. That
    workspace's ``cargo build`` then writes the binary under its own
    ``target/<profile>/``, so the final path is
    ``<spec_dir>/target/plushie-renderer/target/<profile>/<binary_name>``.
    The Python SDK's :func:`plushie.binary.resolve` looks for the stable
    project-local renderer name under :func:`plushie.binary.download_dir`.
    Also honor ``bin_file`` (from ``[tool.plushie]``) if the app wants the
    binary somewhere else.
    """
    profile = "release" if release else "debug"
    bin_ext = ".exe" if sys.platform in ("win32", "cygwin") else ""
    built = (
        spec_dir
        / "target"
        / "plushie-renderer"
        / "target"
        / profile
        / f"{binary_name}{bin_ext}"
    )
    if not built.is_file():
        raise FileNotFoundError(
            f"cargo plushie build completed but the binary is missing at {built}"
        )

    dest_dir = download_dir()
    dest_dir.mkdir(parents=True, exist_ok=True)
    dest = dest_dir / download_name()
    shutil.copy2(built, dest)
    _ensure_executable(dest)
    print(f"installed: {dest}")

    if bin_file:
        target = Path(bin_file)
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(built, target)
        _ensure_executable(target)
        print(f"installed: {target}")

    return dest


def _ensure_executable(path: Path) -> None:
    """Mark *path* executable on Unix systems. No-op on Windows."""
    if sys.platform in ("win32", "cygwin"):
        return
    mode = path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH
    path.chmod(mode)


def build(
    widgets: list[NativeWidget],
    *,
    binary_name: str,
    source_path: str | None,
    release: bool,
    verbose: bool,
    bin_file: str | None,
    spec_dir: Path = SPEC_DIR,
) -> int:
    """End-to-end build: write spec, shell out to cargo-plushie, install.

    Returns the ``cargo plushie build`` exit code (0 on success).
    """
    # Inject or refresh widget metadata in each widget's Cargo.toml.
    for widget in widgets:
        write_widget_metadata(widget)

    manifest = write_spec_cargo_toml(
        widgets,
        binary_name=binary_name,
        source_path=source_path,
        spec_dir=spec_dir,
    )

    # Untangle the command shape:
    # - PATH install: ("cargo-plushie", []) ->  ["cargo-plushie", "build", ...]
    # - Source path:  ("cargo",        [..., "--"])
    #                 -> ["cargo", "run", ..., "--", "build", ...]
    command, prefix = resolve_cargo_plushie()
    cargo_args = _compose_cargo_command(command, prefix, "build")
    cargo_args += ["--manifest-path", str(manifest.resolve())]
    if release:
        cargo_args.append("--release")
    if verbose:
        cargo_args.append("--verbose")

    print(f"running: {' '.join(cargo_args)}")
    completed = subprocess.run(
        cargo_args,
        capture_output=not verbose,
        check=False,
    )
    if completed.returncode != 0:
        if not verbose:
            if completed.stdout:
                sys.stdout.buffer.write(completed.stdout)
            if completed.stderr:
                sys.stderr.buffer.write(completed.stderr)
        print("cargo plushie build failed", file=sys.stderr)
        return completed.returncode

    install_built_binary(
        spec_dir,
        binary_name=binary_name,
        release=release,
        bin_file=bin_file,
    )
    return 0


def _compose_cargo_command(
    command: str, prefix: list[str], subcommand: str
) -> list[str]:
    """Combine the ``resolve_cargo_plushie`` tuple with a subcommand.

    When ``command`` is ``"cargo-plushie"``, the prefix is empty and the
    subcommand follows directly. When ``command`` is ``"cargo"`` (source
    path branch), the prefix ends with ``"--"`` and the subcommand
    follows after the separator.
    """
    return [command, *prefix, subcommand]


__all__ = [
    "SPEC_DIR",
    "build",
    "install_built_binary",
    "write_spec_cargo_toml",
    "write_widget_metadata",
]
